
path: /Users/chloe/OneDrive/Documents/SMU/Jan 2024/DL/Project/Model  # dataset root dir
train: images  # train images (relative to 'path')
val: images  # val images (relative to 'path')

# Classes
names:
  0: smu logo
